### ISSUE TITLE
Normalize decl v2

### ISSUE THREAD

**Issue by aledovskikh** [gulp-bem/gulp-bem-bundle-builder#5]
Maybe we should normalize bem decl with new notation?

`const decl = require('bem-decl').normalizer('v2');`
`...`
`const declNormalize = data => decl(data).map(e => (e.entity.tech = e.tech, e.entity));`
`bundle.decl = declNormalize(bundle.decl);`
`...`

**Comment by skad0** [comment]
Here we only build bundles. 
Normalization is in [bem-deps.parse](https://github.com/bem-sdk/bem-deps/blob/issue%2373/lib/formats/deps.js/parser.js), which called from [bem-deps.load](https://github.com/bem-sdk/bem-deps/blob/issue%2373/lib/load.js) method in [gulp-bem-src](https://github.com/gulp-bem/gulp-bem-src/blob/master/index.js) or in development [gulp-bem-src](https://github.com/gulp-bem/gulp-bem-src/blob/add_deps_as_dep/index.js#L98).

**Comment by qfox** [comment]
> Maybe we should normalize bem decl with new notation?

I guess we should do it in [`fs-bundler`](https://github.com/gulp-bem/gulp-bem-bundler-fs) or [`bem-bundle`](https://github.com/bem-sdk/bem-bundle) package.

> const declNormalize = data => decl(data).map(e => (e.entity.tech = e.tech, e.entity));

It's a big question what fields we should left in [`bem-entity`](https://github.com/bem-sdk/bem-entity-name) object by default. But it's an off-topic for this module.

**Comment by qfox** [comment]
Feels like we have found a form:
`{entity: {block: String, elem: String, mod: {name: String, val: String}}, tech: String}`
but still need a name.

At the moment we want to name it BemCell or BemCytos, but it's another story ;-)
