### ISSUE TITLE
Не ставится сам gulp-bem-bundle-builder

### ISSUE THREAD

**Issue by tuchanemo** [gulp-bem/gulp-bem-bundle-builder#6]
Подправьте, пож. packaje.json в части gulp-bem-src

**Comment by skad0** [comment]
Вот тут фикс #4.
У нас тут "эктив девелопмент", поэтому пока что тянемся из веток

**Comment by qfox** [comment]
Кажется, что проблема решена уже давно, но забыли отписаться.

Если есть возможность — попробуйте текущую версию.
